### ISSUE TITLE
Fix and simplify continuous integration

### ISSUE THREAD

**Issue by jcfr** [Slicer/SlicerExecutionModel#136]
As of August 13th 2021, all jobs are failing:

![image](https://user-images.githubusercontent.com/219043/129404632-2ef37226-adca-4afd-b108-5d5988433412.png)

Source: https://app.circleci.com/pipelines/github/Slicer/SlicerExecutionModel/19/workflows/ed1fad58-f7e9-4df7-8887-ddf82dd7e454

Suggested plan:

* Remove these obsolete jobs:

  https://github.com/Slicer/SlicerExecutionModel/blob/f19d6e88a94ba8f31ddafcff4adf185fe90d7e72/.circleci/config.yml#L56-L58

* Update `itk-master_use_system_libraries-off` docker image

* Add `itk-v5.1.2_use_system_libraries-off` and  `itk-v5.2.1_use_system_libraries-off`

For more details:
* https://github.com/Slicer/SlicerExecutionModel#adding-or-updating-a-testing-environment
* https://github.com/Slicer/SlicerExecutionModel/tree/master/test

**Comment by hjmjohnson** [comment]
Is this still outstanding?

**Comment by jcfr** [comment]
> Is this still outstanding?

Indeed, it needed to be address. This ended up being more time consuming than anticipated.
