### ISSUE TITLE
KWSys / itksys no longer has a SharedForward.h.in file

### ISSUE THREAD

**Issue by aylward** [Slicer/SlicerExecutionModel#138]
ITK has updated its version of KWSys (the source of itksys).  

https://github.com/InsightSoftwareConsortium/ITK/commit/2c45eec4b39cd8b2a0a1b0dc2a6e4182b73bd91f

That update introduced a version of KWSys that does not contain the SharedForward.h.in file, as required by GenerateCLPLauncher.

https://github.com/Slicer/SlicerExecutionModel/blob/bd2efa9e70900483e6c26a54d7108d97bf36f740/GenerateCLP/GenerateCLPLauncher.c.in#L19

SlicerExecutionModel (specifically the GenerateCLPLauncher) will not compile with ITK master.

**Comment by aylward** [comment]
In the meantime, copying the removed file into src and adding it as a _h file to be configured, in the cmakelists.txt file works.

**Comment by dzenanz** [comment]
> In the meantime, copying the removed file into src and adding it as a _h file to be configured, in the cmakelists.txt file, works.

I am giving this a try.
