### ISSUE TITLE
Add COMPILE_FLAGS argument to SEMMacroBuildCLI 

### ISSUE THREAD

**Issue by finetjul** [Slicer/SlicerExecutionModel#26]
Sometimes it might be useful to disable warnings when compiling a CLI.
The naive manual solution to call ```set_target_properties(${MODULE_NAME}Lib PROPERTIES COMPILE_FLAGS "-Wno-overloaded-virtual")``` fails because "-Dmain-=ModuleEntryPoint" is no longer defined.

**Comment by jcfr** [comment]
I am closing this issue. CMake provides the following command to achieve what is described:

```
set_property(
  TARGET ${MODULE_NAME}Lib
  APPEND PROPERTY COMPILE_FLAGS "-Wno-overloaded-virtual"
  )
```

Using `set_property` specifying `APPEND` is the key.

See also https://cmake.org/cmake/help/v2.8.6/cmake.html#command:set_property
