### ISSUE TITLE
Relax ITK version requirement

### ISSUE THREAD

**Issue by nocnokneo** [Slicer/SlicerExecutionModel#40]
Is ITK v4.5 really required? I was able build against ITK v4.3.1 (using all default build options) and things seem to still work fine (100% tests passed)

**Comment by jcfr** [comment]
@nocnokneo Based on your suggestion, I just pushed a topic. If everything works for you, let me know and I will integrate.

**Comment by nocnokneo** [comment]
Yes, works for me! Thanks.

**Comment by jcfr** [comment]
Fixed in e0085131

**Comment by jcfr** [comment]
Thanks for testing :+1:
