### ISSUE TITLE
find_package() perform in SEMMacroBuildCLI and ITK_LIBRARIES issues

### ISSUE THREAD

**Issue by fbudin69500** [Slicer/SlicerExecutionModel#45]
When using the SEMMacroBuildCLI, the macro perfoms a find_package() step:
https://github.com/Slicer/SlicerExecutionModel/blob/master/CMake/SEMMacroBuildCLI.cmake#L103
This step leads to another find_package() step in UseGenerateCLP.cmake:
https://github.com/Slicer/SlicerExecutionModel/blob/master/GenerateCLP/UseGenerateCLP.cmake.in#L20
In this last step, the CMake variable ITK_LIBRARIES is reset.
This reset could lead to link errors, mostly related to the IO factory mechanism if the ITK_LIBRARIES is used again after calling the SEMMacroBuildCLI, i.e. if one calls the macro multiple times to compile multiple CLIs in the same CMakeLists.txt file.
When trying to compile the example available here (branch ITKLinkError):
https://github.com/fbudin69500/3D4DImageConversion/blob/ITKLinkError/CMakeLists.txt
It results in linking error messages:
Linking CXX executable bin/4DTo3DImages
lib/lib4DTo3DImagesLib.a(4DTo3DImages.cxx.o):(.data+0x3a0): undefined reference to `itk::NiftiImageIOFactoryRegister__Private()'
lib/lib4DTo3DImagesLib.a(4DTo3DImages.cxx.o):(.data+0x3a8): undefined reference to `itk::NrrdImageIOFactoryRegister__Private()'
lib/lib4DTo3DImagesLib.a(4DTo3DImages.cxx.o):(.data+0x3b0): undefined reference to `itk::MetaImageIOFactoryRegister__Private()'

One easy solution for the user is to save the value of the ITK_LIBRARIES in a different variable. However, this should be done directly in SEMMacroBuild.

This issue is partly related to:
https://github.com/Slicer/SlicerExecutionModel/issues/8

**Comment by jcfr** [comment]
This issue has been addressed by PR #63 integrating https://github.com/Slicer/SlicerExecutionModel/commit/9881cb527bb2300db85165165d561e4d48f6ac4c
