### ISSUE TITLE
Create a Docker Organization for Pull Request #46

### ISSUE THREAD

**Issue by LucasGandel** [Slicer/SlicerExecutionModel#47]
Pull Request #46 is adding CircleCI verification to this repository using Docker.
The actual Docker repository is a private one ( https://hub.docker.com/r/lucasgandel/slicerexecutionmodel/ ) and should be replaced by a new Organization for SlicerExecutionModel.
Once this organization is created, changes can be made to the pull request to point to that new repository.

**Comment by jcfr** [comment]
Closing. Organization now exists. See https://hub.docker.com/r/slicer/slicerexecutionmodel/
