### ISSUE TITLE
Add CLI Support for the new vtkMRMLTableNode. 

### ISSUE THREAD

**Issue by kevinwangcanada** [Slicer/SlicerExecutionModel#54]
We are creating a new vtkMRMLTableNode. See Slicer issue #3912 at http://na-mic.org/Mantis/view.php?id=3912
This ticket will track the development to add CLI support for this new data type in SEM.

**Comment by jcfr** [comment]
:+1:  Sounds good. Now there is CI testing for the SlicerExecutionModel, it should be easier to check new changes behave well.

**Comment by kevinwangcanada** [comment]
Hi, it seems that this feature is not required any more. vtkMRMLTableNode just uses the existing colour table CLI interface so no need to change Slicer Execution Model. Please close the issue. Thanks.

**Comment by jcfr** [comment]
Sounds good. Thanks for closing the issue.
