### ISSUE TITLE
Error while compiling with ITKv4.9.0

### ISSUE THREAD

**Issue by juanprietob** [Slicer/SlicerExecutionModel#67]
Compilation error when building SlicerExecutionModel in a x86_64 GNU/Linux system. 

```
[  7%] Building CXX object ModuleDescriptionParser/CMakeFiles/ModuleDescriptionParser.dir/ModuleDescriptionParser.cxx.o
In file included from include/ITK-4.9/expat.h:11:0,
                 from SlicerExecutionModel/ModuleDescriptionParser/ModuleDescriptionParser.cxx:24:
include/ITK-4.9/expatDllConfig.h:5:30: fatal error: itk_expat_mangle.h: No such file or directory
compilation terminated.
```

**Comment by jcfr** [comment]
This PR should fix the problem. See https://github.com/Slicer/SlicerExecutionModel/pull/63

After you confirm we will integrate.

**Comment by jcfr** [comment]
Note: Currently travelling, will be back in the office on Monday

**Comment by jcfr** [comment]
Fix has been integrated into master

Slicer will be updated shortly.

**Comment by jcfr** [comment]
Having an other look, problem has been fixed in ITK.
See https://github.com/InsightSoftwareConsortium/ITK/commit/8aa7f97
