### ISSUE TITLE
OUTPUT_DIRECTORY variables cannot be changed

### ISSUE THREAD

**Issue by fbudin69500** [Slicer/SlicerExecutionModel#7]
SlicerExecutionModel_DEFAULT_CLI_*_OUTPUT_DIRECTORY and SlicerExecutionModel_DEFAULT_CLI_INSTALL_*_DESTINATION variables' default value is used when using SEMMacroBuildCLI.cmake because of   find_package(SlicerExecutionModel REQUIRED GenerateCLP) (line 100). One solution is to set those varialbes as CACHE variables when setting their default value in SlicerExecutionModelConfig.cmake.

**Comment by jcfr** [comment]
Developer can set output directory with the following methods (where last method has the highest priority ):
* configuring SlicerExecutionModel project setting variables `SlicerExecutionModel_DEFAULT_CLI_(RUNTIME|LIBRARY|ARCHIVE)_OUTPUT_DIRECTORY`
* setting variables `SlicerExecutionModel_CLI_(RUNTIME|LIBRARY|ARCHIVE)_OUTPUT_DIRECTORY` in the current scope before including `SEMMacroBuildCLI`
* specifying `(RUNTIME|LIBRARY|ARCHIVE)_OUTPUT_DIRECTORY` option to `SEMMacroBuildCLI`

The same applies for `SlicerExecutionModel_CLI_INSTALL_(RUNTIME|LIBRARY|ARCHIVE)_DESTINATION`
