### ISSUE TITLE
GenerateCLP should be independent of ITKv4

### ISSUE THREAD

**Issue by jcfr** [Slicer/SlicerExecutionModel#8]
ITK is needed only because `itksys` is used. Instead, `kwsys` should either be integrated (copying the source :( or using a git submodule :) )

**Comment by fbudin69500** [comment]
Actually, `ModuleDescriptionParser`needs an XML parser and uses ITK IO for that, so removing ITK would be more complex than previously thought. Closing this issue.

**Comment by jcfr** [comment]
We could also vendorize the code if that makes things easier
